import 'package:pieces_os_client/api.dart';
import 'package:test/test.dart';

/// tests for ConnectorApi
void main() {
  // final instance = ConnectorApi();

  group('[Localhost] Tests for ConnectorApi', () {

    // /connect [POST]
    //
    // Abstracts a bootup/connection for a specific context.
    //
    test('Test /connect Endpoint', () async {
    Future<Context ? > connect({ SeededConnectorConnection? seededConnectorConnection }) async {
            Context?  returnable = Context.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        connect(  seededConnectorConnection: seededConnectorConnection  );
    });

    // /{application}/intention [POST]
    //
    // Allows you to send a SeededAsset for future comparison.
    //
    test('Test /intention Endpoint', () async {
    Future<String ? > intention( String application, { SeededConnectorAsset? seededConnectorAsset }) async {
            String?  returnable = String.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        intention(application ,   seededConnectorAsset: seededConnectorAsset  );
    });

    // /onboarded [POST]
    //
    // A central endpoint to manage updates to the onboarding process.
    //
    test('Test /onboarded Endpoint', () async {
    Future<String ? > onboarded( String application, { bool? body }) async {
            String?  returnable = String.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        onboarded(application ,   body: body  );
    });

    // /{application}/reaction [POST]
    //
    // This will respond to the output generated by the /suggest endpoint.
    //
    test('Test /react Endpoint', () async {
    Future<String ? > react( String application, { Reaction? reaction }) async {
            String?  returnable = String.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        react(application ,   reaction: reaction  );
    });

    // /{application}/suggestion [POST]
    //
    // Invoked whenever a code snippet is copied from an integration. For instance, if a JetBrains user copies code, this endpoint can be called to assess whether to suggest reusing a piece (if reuse is true, the endpoint provides assets that the user may consider using), saving the code snippet, or taking no action.   **Note: This endpoint could potentially accept a SeededFormat for the request body if required.
    //
    test('Test /suggest Endpoint', () async {
    Future<Suggestion ? > suggest( String application, { SeededConnectorCreation? seededConnectorCreation }) async {
            Suggestion?  returnable = Suggestion.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        suggest(application ,   seededConnectorCreation: seededConnectorCreation  );
    });
  });
}
