import 'package:pieces_os_client/api.dart';
import 'package:test/test.dart';

/// tests for WorkstreamSummariesApi
void main() {
  // final instance = WorkstreamSummariesApi();

  group('[Localhost] Tests for WorkstreamSummariesApi', () {

    // /workstream_summaries/search [POST]
    //
    // This will search your workstream_summaries for a specific workstream_summary  note: we will just search the summary value(which is an annotation)
    //
    test('Test /searchWorkstreamSummaries Endpoint', () async {
    Future<SearchedWorkstreamSummaries ? > searchWorkstreamSummaries({ bool? transferables, SearchInput? searchInput }) async {
            SearchedWorkstreamSummaries?  returnable = SearchedWorkstreamSummaries.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        searchWorkstreamSummaries(  transferables: transferables ,  searchInput: searchInput  );
    });

    // /workstream_summaries/batch [POST]
    //
    // Batch fetch workstream summaries by providing a list of UUIDs. This endpoint allows for efficient retrieval of multiple workstream summaries in a single request. The response will include successfully fetched summaries and a list of any UUIDs that were not found. Note: If a UUID in the batch doesn't exist, it will be caught and added to the notFound list in the response. The transferables query parameter defaults to false for performance optimization. 
    //
    test('Test /workstreamSummariesBatch Endpoint', () async {
    Future<WorkstreamSummariesBatchOutput ? > workstreamSummariesBatch( WorkstreamSummariesBatchInput workstreamSummariesBatchInput, { bool? transferables }) async {
            WorkstreamSummariesBatchOutput?  returnable = WorkstreamSummariesBatchOutput.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        workstreamSummariesBatch(workstreamSummariesBatchInput ,   transferables: transferables  );
    });

    // /workstream_summaries/create/summary [POST]
    //
    // This will create an autogenerate summary based off of ranges, and events  for now we will(XOR) ie either  1. generate based on events 2. or we will generate based on ranges  in the future we can merge these  in the future we can add 1. summaries 2. sources
    //
    test('Test /workstreamSummariesCreateAutogeneratedWorkstreamSummary Endpoint', () async {
    Future<WorkstreamSummary ? > workstreamSummariesCreateAutogeneratedWorkstreamSummary({ bool? transferables, AutoGeneratedWorkstreamSummaryInput? autoGeneratedWorkstreamSummaryInput }) async {
            WorkstreamSummary?  returnable = WorkstreamSummary.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        workstreamSummariesCreateAutogeneratedWorkstreamSummary(  transferables: transferables ,  autoGeneratedWorkstreamSummaryInput: autoGeneratedWorkstreamSummaryInput  );
    });

    // /workstream_summaries/create/from_message [POST]
    //
    // Create a workstream summary from a conversation message.
    //
    test('Test /workstreamSummariesCreateFromMessage Endpoint', () async {
    Future<WorkstreamSummariesCreateFromMessageOutput ? > workstreamSummariesCreateFromMessage({ WorkstreamSummariesCreateFromMessageInput? workstreamSummariesCreateFromMessageInput }) async {
            WorkstreamSummariesCreateFromMessageOutput?  returnable = WorkstreamSummariesCreateFromMessageOutput.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        workstreamSummariesCreateFromMessage(  workstreamSummariesCreateFromMessageInput: workstreamSummariesCreateFromMessageInput  );
    });

    // /workstream_summaries/create [POST]
    //
    // This will create a new WorkstreamSummary in the database.
    //
    test('Test /workstreamSummariesCreateNewWorkstreamSummary Endpoint', () async {
    Future<WorkstreamSummary ? > workstreamSummariesCreateNewWorkstreamSummary({ bool? transferables, SeededWorkstreamSummary? seededWorkstreamSummary }) async {
            WorkstreamSummary?  returnable = WorkstreamSummary.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        workstreamSummariesCreateNewWorkstreamSummary(  transferables: transferables ,  seededWorkstreamSummary: seededWorkstreamSummary  );
    });

    // /workstream_summaries/{workstream_summary}/delete [POST]
    //
    // This will delete a specific workstream_summary from the database!
    //
    test('Test /workstreamSummariesDeleteSpecificWorkstreamSummary Endpoint', () async {
    Future workstreamSummariesDeleteSpecificWorkstreamSummary( String workstreamSummary) async {
             returnable = .fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        workstreamSummariesDeleteSpecificWorkstreamSummary(workstreamSummary );
    });

    // /workstream_summaries/child/identifiers [GET]
    //
    // This will get all workstream summary child identifiers.
    //
    test('Test /workstreamSummariesGetChildIdentifiers Endpoint', () async {
    Future<FlattenedWorkstreamSummaries ? > workstreamSummariesGetChildIdentifiers({ bool? transferables }) async {
            FlattenedWorkstreamSummaries?  returnable = FlattenedWorkstreamSummaries.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        workstreamSummariesGetChildIdentifiers(  transferables: transferables  );
    });

    // /workstream_summaries/parent/identifiers [GET]
    //
    // This will get all workstream summary parent identifiers.
    //
    test('Test /workstreamSummariesGetParentIdentifiers Endpoint', () async {
    Future<FlattenedWorkstreamSummaries ? > workstreamSummariesGetParentIdentifiers({ bool? transferables }) async {
            FlattenedWorkstreamSummaries?  returnable = FlattenedWorkstreamSummaries.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        workstreamSummariesGetParentIdentifiers(  transferables: transferables  );
    });

    // /workstream_summaries/merge [POST]
    //
    // This endpoint takes multiple workstream summaries and merges them together into a brand new summary.
    //
    test('Test /workstreamSummariesMerge Endpoint', () async {
    Future<WorkstreamSummariesMergeOutput ? > workstreamSummariesMerge({ WorkstreamSummariesMergeInput? workstreamSummariesMergeInput }) async {
            WorkstreamSummariesMergeOutput?  returnable = WorkstreamSummariesMergeOutput.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        workstreamSummariesMerge(  workstreamSummariesMergeInput: workstreamSummariesMergeInput  );
    });

    // /workstream_summaries [GET]
    //
    // This will get a snapshot of all your workstream summaries.
    //
    test('Test /workstreamSummariesSnapshot Endpoint', () async {
    Future<WorkstreamSummaries ? > workstreamSummariesSnapshot({ bool? transferables }) async {
            WorkstreamSummaries?  returnable = WorkstreamSummaries.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        workstreamSummariesSnapshot(  transferables: transferables  );
    });

    // /workstream_summaries/stream/identifiers [WS]
    //
    // Provides a WebSocket connection that emits changes to your workstream_summary identifiers (UUIDs).
    //
    test('Test /workstreamSummariesStreamIdentifiers Endpoint', () async {
    Future<StreamedIdentifiers ? > workstreamSummariesStreamIdentifiers() async {
            StreamedIdentifiers?  returnable = StreamedIdentifiers.fromJson();
            print(returnable?.toJson());
            return returnable;
        }

        // Helpful Variables here for use with responses below
        // TODO - Need to check if it is nullable or not

        workstreamSummariesStreamIdentifiers();
    });
  });
}
