//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//
// @dart=2.18

// ignore_for_file: unused_element, unused_import
// ignore_for_file: always_put_required_named_parameters_first
// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars

part of pieces_os_client;

class AutoGeneratedWorkstreamSummaryInput {
  /// Returns a new [AutoGeneratedWorkstreamSummaryInput] instance.
  AutoGeneratedWorkstreamSummaryInput({
    this.anonymousRanges = const [],
    this.events,
    this.schema,
  });

  List<AnonymousTemporalRange> anonymousRanges;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  FlattenedWorkstreamEvents? events;

  ///
  /// Please note: This property should have been non-nullable! Since the specification file
  /// does not include a default value (using the "default:" property), however, the generated
  /// source code must fall back to having a nullable type.
  /// Consider adding a "default:" property in the specification file to hide this note.
  ///
  EmbeddedModelSchema? schema;

  @override
  bool operator ==(Object other) => identical(this, other) || other is AutoGeneratedWorkstreamSummaryInput &&
    _deepEquality.equals(other.anonymousRanges, anonymousRanges) &&
    other.events == events &&
    other.schema == schema;

  @override
  int get hashCode =>
    // ignore: unnecessary_parenthesis
    (anonymousRanges.hashCode) +
    (events == null ? 0 : events!.hashCode) +
    (schema == null ? 0 : schema!.hashCode);

  @override
  String toString() => 'AutoGeneratedWorkstreamSummaryInput[anonymousRanges=$anonymousRanges, events=$events, schema=$schema]';

  Map<String, dynamic> toJson() {
    final json = <String, dynamic>{};
      json[r'anonymous_ranges'] = this.anonymousRanges;
    if (this.events != null) {
      json[r'events'] = this.events;
    } else {
      json[r'events'] = null;
    }
    if (this.schema != null) {
      json[r'schema'] = this.schema;
    } else {
      json[r'schema'] = null;
    }
    return json;
  }

  /// Returns a new [AutoGeneratedWorkstreamSummaryInput] instance and imports its values from
  /// [value] if it's a [Map], null otherwise.
  // ignore: prefer_constructors_over_static_methods
  static AutoGeneratedWorkstreamSummaryInput? fromJson(dynamic value) {
    if (value is Map) {
      final json = value.cast<String, dynamic>();

      // Ensure that the map contains the required keys.
      // Note 1: the values aren't checked for validity beyond being non-null.
      // Note 2: this code is stripped in release mode!
      assert(() {
        requiredKeys.forEach((key) {
          assert(json.containsKey(key), 'Required key "AutoGeneratedWorkstreamSummaryInput[$key]" is missing from JSON.');
          assert(json[key] != null, 'Required key "AutoGeneratedWorkstreamSummaryInput[$key]" has a null value in JSON.');
        });
        return true;
      }());

      return AutoGeneratedWorkstreamSummaryInput(
        anonymousRanges: AnonymousTemporalRange.listFromJson(json[r'anonymous_ranges']),
        events: FlattenedWorkstreamEvents.fromJson(json[r'events']),
        schema: EmbeddedModelSchema.fromJson(json[r'schema']),
      );
    }
    return null;
  }

  static List<AutoGeneratedWorkstreamSummaryInput> listFromJson(dynamic json, {bool growable = false,}) {
    final result = <AutoGeneratedWorkstreamSummaryInput>[];
    if (json is List && json.isNotEmpty) {
      for (final row in json) {
        final value = AutoGeneratedWorkstreamSummaryInput.fromJson(row);
        if (value != null) {
          result.add(value);
        }
      }
    }
    return result.toList(growable: growable);
  }

  static Map<String, AutoGeneratedWorkstreamSummaryInput> mapFromJson(dynamic json) {
    final map = <String, AutoGeneratedWorkstreamSummaryInput>{};
    if (json is Map && json.isNotEmpty) {
      json = json.cast<String, dynamic>(); // ignore: parameter_assignments
      for (final entry in json.entries) {
        final value = AutoGeneratedWorkstreamSummaryInput.fromJson(entry.value);
        if (value != null) {
          map[entry.key] = value;
        }
      }
    }
    return map;
  }

  // maps a json object with a list of AutoGeneratedWorkstreamSummaryInput-objects as value to a dart map
  static Map<String, List<AutoGeneratedWorkstreamSummaryInput>> mapListFromJson(dynamic json, {bool growable = false,}) {
    final map = <String, List<AutoGeneratedWorkstreamSummaryInput>>{};
    if (json is Map && json.isNotEmpty) {
      // ignore: parameter_assignments
      json = json.cast<String, dynamic>();
      for (final entry in json.entries) {
        map[entry.key] = AutoGeneratedWorkstreamSummaryInput.listFromJson(entry.value, growable: growable,);
      }
    }
    return map;
  }

  /// The list of required keys that must be present in a JSON.
  static const requiredKeys = <String>{
  };
}

